### ISSUE TITLE
Implement Warm Backup Storage Solution (Data Backup Plan)

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/nucleus#91]
### 💡 Description

Per Data Backup Plan, we need a copy of all archive data in Glacier or Deep Archive in order to have a warm backup.

### ⚔️ Parent Epic / Related Tickets

- [x] document proposed solution on Atlassian wiki (link from Data Backup Plan on JPL wiki)
- [x] prepare presentation of proposal for PDS MC F2F in November
- [x] implement solution in Nucleus
   - https://github.com/NASA-PDS/planetary-data-cloud/issues/75
   - https://github.com/NASA-PDS/nucleus/issues/73

**Comment by jordanpadams** [comment]
📆 05/2024 status: Start delayed 1 sprint due to delays in https://github.com/NASA-PDS/nucleus/issues/93. No impact on build expected.

**Comment by jordanpadams** [comment]
📆 05/2024 status: End date delayed and additional sprint due to delays in https://github.com/NASA-PDS/nucleus/issues/93. TBD impacts on Nucleus tasks

**Comment by jordanpadams** [comment]
@ramesh-maddegoda @viviant100 ☝

**Comment by jordanpadams** [comment]
📆 07/2024 status: Delays continue an additional sprint due to delays in Nucleus https://github.com/NASA-PDS/nucleus/issues/93. No impact on remaining tasks since this is not required for initial cloud migration activities. It will be done prior to CSS going live in production in eaerly FY25.

**Comment by jordanpadams** [comment]
@ramesh-maddegoda @viviant100 ☝

**Comment by jordanpadams** [comment]
📆 08/2024 status: In work. On schedule for completion by end of sprint.

**Comment by jordanpadams** [comment]
This is done. Draft of the document has been created.
